name: Mayan CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          sudo set -a && . ./config.env && set +a
          sudo apt-get -qq update
          sudo apt-get install -qq make python3-venv python3-dev
          python3 -m venv venv
          . venv/bin/activate
          pip install pip
          pip install -r requirements/build.txt
          make python-wheel

  base_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          sudo set -a && . ./config.env && set +a
          sudo echo "deb http://deb.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list
          sudo echo "deb-src http://deb.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt-get install --yes --no-install-recommends --target-release buster-backports -qq libreoffice-calc-nogui libreoffice-draw-nogui libreoffice-impress-nogui libreoffice-math-nogui libreoffice-writer-nogui
          sudo apt-get install --yes --no-install-recommends -qq curl exiftool gcc ghostscript gnupg1 graphviz libfuse2 libjpeg-dev libmagic1 libpng-dev libtiff-dev make poppler-utils python3-venv python3-dev sane-utils tesseract-ocr tesseract-ocr-deu
          python3 -m venv venv
          . venv/bin/activate
          pip install pip==$PYTHON_PIP_VERSION
          pip install --requirement requirements.txt --requirement requirements/testing-base.txt --requirement requirements/build.txt

          
